go.property("max_radius", 40)
go.property("min_radius", 2)
go.property("dim_speed", 0.05)

function update(self, dt)
	local pos = go.get_position "player"
	local cam = go.get_position "camera"
	pos = pos - cam
	pos.x = math.min(math.max(0, pos.x), 480)
	pos.y = math.min(math.max(0, pos.y), 854)
	pos = pos + cam
	go.set_position(pos)

	local scale = self.max_radius + cam.y * self.dim_speed
	scale = math.max(scale, self.min_radius)
	go.set_scale(scale)
end
